[build]
  command = "./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/gary-stroup-developer/sessions"
  GO111MODULE = "on"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/web/:splat"
  status = 200